# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build done" > result.txt
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.txt
