# .github/workflows/child.yml
name: Child Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to greet"
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi, ${{ inputs.name }}"
