# .github/workflows/target.yml
name: Target Workflow

on:
  repository_dispatch:
    types: [custom-trigger]

jobs:
  handle-dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered via repository_dispatch!"
