# .github/workflows/trigger.yml
name: Trigger API Workflow

on:
  push:
    branches: [main]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/<OWNER>/<REPO>/actions/workflows/child.yml/dispatches \
            -d '{"ref":"main", "inputs":{"name":"Thatchayaini"}}'
